### ISSUE TITLE
PROP variable naming inconsistency in toolshelf

### ISSUE THREAD

**Issue by ArchageXIII** [IngoClemens/blender#2]
Amazing tool, small bit of feedback, I think I have this right.

If I add a single property in tool shelf to reference it in code, it is PROP

if I add 2 properties the first property is referenced as PROP1 the second as PROP2

Took me a little bit of work to figure that out as the examples all use 2 variables so start at PROP1 and I was getting errors trying to reference PROP1 with a single property, might be better to have it consistent for the starting numbering but then I guess that might break existing scripts but could perhaps start at PROP1 and point PROP to that so anyone using PROP still worked.

Also adding property's if you miss type values like string as strinh or put a ; in the wrong place like at the end it crashes the plugin and you have to go into the json file to fix it and then restart the plugin.  Not a major problem but for new users / developers it might be a bit tricky to figure out.

but just minor points, such a cool tool thanks for creating it!

Mark

**Comment by IngoClemens** [comment]
Hi Mark,

thanks for the feedback. Regarding the property names you are correct and I observed this myself.
I will see what I can do.
And yes, there is no real error checking for wrong values if I recall. But thanks for bringing this to my attention.
I will report back when it's fixed.

Cheers,
Ingo

**Comment by ArchageXIII** [comment]
thanks Ingo, 

Once I finish this piece of work I'm doing and have some time I'll have a look as well, it would be really cool to extend it a bit so it's easy to send visual feedback for tasks / errors etc. back to the user from the script as well, I'll see if I can do something there.

thanks again for this, it's a great tool.

**Comment by IngoClemens** [comment]
I just updated the tool to version 0.10.0 addressing the aforementioned issues.
Namely:

- Property placeholders for single properties can now also be PROP1, to be consistent with the formatting for multiple properties.
- Added a basic spell check for string and boolean property types.
- Fixed that entries ending with a colon caused the tool to fail.
- Added Substance3DInBlender to the black list of add-ons.

Just as a note: The written documentation states that for single properties you can also use PROP, it just might be that the videos might not mention it. But I also added that PROP1 is now also possible.

The basic spell check is matching the words string, true and false against a set of three characters. For example this converts 'treu' to 'true', 'flaes' to 'false' and 'srtng' to 'string'.
