### ISSUE TITLE
Addon not working after updating to 2.0.0. The brush does not apply the weight smooth at all

### ISSUE THREAD

**Issue by rccola97** [IngoClemens/blender#4]
The previous version was working fine up until I updated to the latest 2.0.0 version, tried using it but it doesn't seem to apply the smooth weights no matter how much I stroke the brush. Can't really tell if this is a problem on my end or the addon. I tried it on multiple rigs but it doesn't seem to be working at all.

Love the addon and have been using the Maya variant of this from way back. I would appreciate it if this issue would be resolved real soon.

**Comment by IngoClemens** [comment]
Can you please contact me via email regarding this issue. You can use the contact form on braverabbit.com. Thanks.
